server:
  port: 8080

spring:
  flyway:
    baseline-on-migrate: true
    user: postgres
    password: 1
    out-of-order: true
  datasource:
    driver-class-name: org.h2.Driver #org.postgresql.Driver
    username: postgres
    password: 1
    url: jdbc:h2:mem:files #jdbc:postgresql://localhost:5432/files
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true